### ISSUE TITLE
Can you add some strings for translate?

### ISSUE THREAD

**Issue by exotickg1** [rainlab/user-plugin#89] opened 2015-06-27 13:48 UTC
The plugin still has not translated strings. E.g.:
![Not Translated strings](http://i.gyazo.com/65325e64ece92ddfe87fb60558414097.png)

**Comment by LukeTowers** [comment] 2017-02-03 02:20
Duplicate of #223

**Closed by LukeTowers** 2017-02-03 02:20 UTC
Labels: duplicate

**Comment by daftspunk** [comment] 2017-02-09 19:59
We won't be translating the component default markup, it is designed to be a usage example. You should override it, see the docs for how to do this. Then check the RainLab.Translate plugin if you need to translate it to several other languages.
