### ISSUE TITLE
Log in backend redirect to the login of my application

### ISSUE THREAD

**Issue by marthib** [rainlab/user-plugin#274] opened 2017-06-29 13:14 UTC
Hello,
I have the same issue of that:

https://github.com/rainlab/user-plugin/issues/258

I've created plugins/rainlab/user/components/CustomAccount.php
```
<?php namespace RainLab\User\Components;

use RainLab\User\Components\Account;
class CustomAccount extends Account
{
    public function onCustomSignin()
    {
        try {
            parent::onSignin();

            $redirectUrl = null;

            // user defined component property
            if ($redirect_value = $this->property('redirect')) {
                $redirectUrl = $this->pageUrl($redirect_value);
            }

            // give preference to request input, otherwise use user defined component property
            $redirectUrl = input('redirect', $redirectUrl);

            // prefer not to use Redirect::intended if we have a user defined url
            if ($redirectUrl) {
                return \Redirect::to($redirectUrl);
            }

            // current method as fallback
            return \Redirect::intended($redirectUrl);

        } catch (\Exception $ex) {
            if (\Request::ajax()) throw $ex;
            else \Flash::error($ex->getMessage());
        }
    }
}
```
I don't know if I need to create à repository customaccount for the component, so, I've tried the two ways. 

I've registered the components in the Plugin.php file:

```
public function registerComponents()
    {
        return [
            'RainLab\User\Components\Session'       => 'session',
            'RainLab\User\Components\Account'       => 'account',
            'RainLab\User\Components\CustomAccount' => 'customaccount',
            'RainLab\User\Components\ResetPassword' => 'resetPassword'
        ];
    }
```

In the login page of my application, I've add:

```
[customaccount]
redirect = "Accueil"
==
```

And finally I've modified plugins/rainlab/user/components/customaccount/signin.htm

```
{% set spelling = __SELF__.langue %}

<form
        data-request="onCustomSignin" class="clearfix" data-request-validate>
    <div class="form-group">
        <label for="userSigninLogin">{{ spelling.email }}</label>
        <input
                name="login"
                type="text"
                class="form-control"
                id="userSigninLogin"
                placeholder="{{ spelling.placeholder_email }}" />
    </div>

    <div class="form-group">
        <label for="userSigninPassword">{{ spelling.password }}</label>
        <input
                name="password"
                type="password"
                class="form-control"
                id="userSigninPassword"
                placeholder="{{ spelling.placeholder_password }}" />
    </div>

    <button type="submit" class="btn btn-default btn-lg" data-request-data="redirect: '/accueil'">{{spelling.sign_in}}</button>

</form>
```

The issue is always there... I don't understand why

**Comment by LukeTowers** [comment] 2017-06-29 13:18
@marthib Please don't create new issues for the same problem, just add your comments to the original issue. Ideally you shouldn't have to use the temporary solution presented in #258, it should be fixed in the plugin so that the root cause doesn't happen. Also, you should never add code directly to a third party plugin, whenever it gets updated your changes will be obliterated.

**Closed by LukeTowers** 2017-06-29 13:18 UTC
