### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by Asinox** [rainlab/user-plugin#223] opened 2016-11-21 20:18 UTC
This is weird, im using Spanish lang, in my config/app.php my locale is "ES"
`` 'locale' => 'es'``

But all errors are displaying English...

Any idea?

Thanks

**Comment by daftspunk** [comment] 2016-11-24 21:19
The `es` translations exist. Which error specifically?

This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by Asinox** [comment] 2016-12-23 00:45
OK, let me try to explain this thing.

My settings (config/app.php) locate is in "es".

I have signin/register/forgot-password pages.

For the signin and register pages there are partials because i don't need register a signin forms in the same page.

So, any validation error is showing up in English, the only validation error that came in Spanish was the email validation in forgot-password page.

And btw talking about forgot-password page this text: _"Lost your password? No problem! Enter your email address to verify your account."_, don't have any translation (i think), is there always in English.

I don't know if this is clear for you, but is a simple thing, there is not validation error coming in Spanish (or i don't know how to setup this plugin)

User Plugin version: 1.3.3
System version: 382 

Any idea about how fix this?

Thank you!

**Comment by eXpl0it3r** [comment] 2017-01-06 11:13
The components have hard coded English words in it, see issue #229.

**Comment by LukeTowers** [comment] 2017-02-03 02:04
The reason components aren't translated is because components are for the frontend and the default translation refers to the backend locale. I'd like to get @daftspunk's input on this

**Comment by rajakhoury** [comment] 2017-02-09 18:42
Same Issue here with the RainLab Auth Manager. For example in `findUserByCredentials` throws an exception hardcoded 'A user was not found with the given credentials.' - While using the Translate plugin cannot find a way to display this message in the default App locale. The User plugin Lang directory has an `invalid_user` localization but it is useless because the it is hardcoded - All I can think off is completely re-write the Auth Manager to add this feature..

**Comment by daftspunk** [comment] 2017-02-09 19:59
@rajakhoury This is a debug error, set the `app.debug` config mode to FALSE and the message will change.

**Comment by rajakhoury** [comment] 2017-02-09 20:26
@daftspunk Thanks for the reply. Yes, I set it to false and the message changed to `The details you entered did not match our records. Please double-check and try again.` set in the  October\Rain\Auth\AuthException class. Please bear with me, any hint how do we override this for the Auth Exceptions.. ?

**Comment by daftspunk** [comment] 2017-02-09 20:29
That's odd because I thought this exception was translated. At least, it should be, will look in to it.

**Comment by der-On** [comment] 2017-05-24 19:10
This exception comes from `October\Rain\Auth\AuthException` and is hard coded. Basically this means it's out of the scope of this plugin to translate the exception. Are there any events one could listen for to Translate the exception message, before it's send to the frontend?

**Comment by der-On** [comment] 2017-05-24 19:27
Found out how to catch the AuthException and return a translated message:

```php
App::error(function (AuthException $exception) {
    return Lang::get('your.plugin::lang.exception');
});
```

**Comment by LukeTowers** [comment] 2017-10-26 21:49
Closing as it has been over a month since any activity on this occurred.

**Comment by eXpl0it3r** [comment] 2017-10-27 08:16
Interesting way to "deal" with issues...

**Comment by LukeTowers** [comment] 2017-10-27 15:34
I'm going crazy with the Abandoned tag in order to prompt some movement with these issues. As it stands right now the core team is way too busy with everything to handle every single issue ourselves.

My solution to this is to poke people into actually taking on the issues that are important to them. If an issue isn't important to them anymore, then they won't do anything and everything will continue as it would have anyways. If it is still important to them, then this will act as a reminder that it still needs to be resolved and hopefully motivate people to try and dig deeper into the issue rather than just assume that the free support of an open source project will solve it for them.

@eXpl0it3r If this is still an issue for you, please try debugging it and make a pull request to solve the issue.

**Comment by meysammahfouzi** [comment] 2018-06-14 14:14
Hi @der-On 

I have come up with a solution which is a hack and is dirtier than yours, but does not need to set `debug` to false:
```
public function onSignin()
{
    try {
        return $this->account->onSignin();
    }
    catch(Exception $e) {
        $m = $e->getMessage();
        if ($m == 'A user was not found with the given credentials.')
            throw new AuthException('No se encontró un usuario con las credenciales especificadas');
        else if ($m == 'A user was found to match all plain text credentials however hashed credential "password" did not match.')
            throw new AuthException('Se encontró que un usuario coincidía con todas las credenciales de texto sin formato, sin embargo, la contraseña de la credencial hash no coincidía.');
        throw new AuthException($m);
    }
}
```

**Comment by LukeTowers** [comment] 2020-11-26 19:38
The correct solution to this issue is to change the Auth Manager class in the Rain library to throw more specific exception classes for each of the potential issues with the authentication process (https://github.com/octobercms/library/blob/develop/src/Auth/Manager.php). Then we can catch those exceptions in this plugin's components and rethrow them with translated messages.

If anyone would like to help out with this, feel free to take a stab at that and submit PRs to the rain library and this plugin.

**Comment by daftspunk** [comment] 2021-08-19 05:28
To address issues in this post:

 Component default markup serves as a minimum viable example on how to implement the component. Translation detracts from it being minimum and there could be numerous ways to implement the translation. This is why they are not shipped with translations. These should be implemented in your theme according to your project requirements.

As of v2.1.5 you can override the failed auth message (when debug mode is FALSE), by using this code

```
AuthException::setDefaultErrorMessage('The login attempt failed');
```

This currently defaults to the language key `backend::lang.auth.invalid_login` and should be translated nicely already.

I hope this helps!

**Closed by daftspunk** 2021-08-19 05:28 UTC
Labels: Status: Review Needed, Type: Bug, help wanted
