### ISSUE TITLE
Custom email seems to be ignored when creating an account for a user

### ISSUE THREAD

**Issue by maartenmachiels** [rainlab/user-plugin#280] opened 2017-08-10 08:17 UTC
Hi, I'm using the User plugin version 1.3.4 in combination with October CMS version 419.

Using the user plugin, I'm creating accounts for some (frontend) users. They receive a welcome mail with this text, even though I have changed it in `/backend/system/mailtemplates`

```
HelloUsername,

A user account has been created for you. Please use the following login and password to sign in:

Login: usermail@address.com
Password: examplePasswordSetByAdmin

After signing in you should change your password as soon as possible.
```

Also please note the lack of a space between `Hello` and `Username`.

In the settings of the user plugin `/backend/system/settings/update/rainlab/user/settings` under Notifications setting a specific e-mailtemplate does not have any effect. The mail always reverts to the above text.

Please note that in my setup I've set it up so that only admins can create user accounts. The e-mail we're talking about is the one that's being sent when the checkmark `Send invitation by email - Sends a welcome message containing login and password information.` is checked.

Could you please look into this? Thanks a bunch.

**Comment by dadigu** [comment] 2017-08-24 12:50
I can confirm that I am also experiencing this behaviour.

**Comment by LukeTowers** [comment] 2017-10-26 21:51
Closing as it has been over a month since any activity on this occurred.

**Closed by LukeTowers** 2017-10-26 21:51 UTC
Labels: Priority: Medium, Status: Review Needed, Type: Unconfirmed Bug
