### ISSUE TITLE
Unknown "Partial"  tag in string template when the send invitation by email is checked in creating a user.

### ISSUE THREAD

**Issue by ronogrimen** [rainlab/user-plugin#326] opened 2018-04-04 03:27 UTC
![image](https://user-images.githubusercontent.com/32258387/38287013-ed6222c6-37fa-11e8-8abd-41fba4fe5a8b.png)

I tried php artisan cache:clear but still it didnt work.

My current build is 432.

**Comment by LukeTowers** [comment] 2018-04-04 04:49
Duplicate of #307

**Closed by LukeTowers** 2018-04-04 04:49 UTC
