### ISSUE TITLE
The password confirmation does not match error message

### ISSUE THREAD

**Issue by Corymillz** [rainlab/user-plugin#412] opened 2019-11-14 21:08 UTC
I created a page and have a registration form in it...`Below is the form

````
title = "Seller-registration"
url = "/seller-registration/:code?"
layout = "default"
is_hidden = 0

[account]
[session]
redirect = "home" 
paramCode = "code"
[session]
==
<?php
use RainLab\User\Models\User;

public function onCheckEmail()
{
    return ['isTaken' => Auth::findUserByLogin(post('email')) ? 1 : 0,];
}

?>
==

{% if not user %}
     <div class="container" style="margin-top: -30px">
        <div class="starter-template" style="margin: -33px">

         <div class="card shadow">
                <div class="card-body">
        
            {% if canRegister %}

    <h3 align="center">Seller Account</h3>    
    <h6 align="center" style="color: grey">Sign Up</h6>
    <hr> 
    {{ form_ajax('onRegister') }}



    <div class="form-label-group">
    <input 
    name="company"
    type="text" 
    id="inputName" 
    class="form-control" 
    placeholder="Company/Business Name" 
    required autofocus
    


    >

    <label for="inputName">Company/Business Name</label>
  </div>



    <div class="form-label-group">
    <input 
    name="email"
    type="email" 
    id="inputEmail" 
    class="form-control" 
    placeholder="Email address" 
    required autofocus
    data-request="onCheckEmail"
    data-request-success="$('#loginTaken').toggle(!!data.isTaken)"
    data-track-input


    >

    <label for="inputEmail">Email address</label>
    <div id="loginTaken" class="alert alert-danger alert-danger-sm" style="display: none"><small>This Email already exist</small>
    
</div>
  </div>


        {% if loginAttribute == "username" %}
            <div class="form-group">
                  <div align="left"><small><b><label for="registerUsername">Username</label></b></small></div>
                <input
                    name="username"
                    type="text"
                    class="form-control form-control-sm field"
                    id="registerUsername"
                    placeholder="Enter your username" />
            </div>
        {% endif %}

      

         <div class="form-label-group">
    <input 
    name="password"
    type="password" 
    id="myInput1" 
   class="form-control" 
    placeholder="Password" 
     autofocus
 
    >

    <label for="registerPassword">Password</label>
  </div>



  <div class="form-label-group">
    <input 
    name='password_confirmation'
    type="password"
    id="myInput1"
   class="form-control" 
    placeholder="Password Confirmation" 
    autofocus
   
    
>

    <label for="inputPassword">Password Confirmation</label>
  </div>

           
    <div align="center"> <button id="shownow" type="submit" style="background-color: #08172A; color: white"  class="btn btn-sm rounded--lg-pill shadow rounded col-6" >Register</button></div>

    {{ form_close() }}


{% else %}
    <!-- Registration is disabled. -->
{% endif %}
</div>
</div>

        </div>
    </div>
````

every time i try to register a new user, i always get the annoying error message 

`The password confirmation does not match`

Although the user is saved and i can log in with the user's credentials. But this error keeps coming up and prevents a redirection to the homepage. I have tried every thing i can including deleting the rules in the user model and  account.php  file but it is still coming up.

**Comment by bennothommo** [comment] 2019-11-15 00:30
Duplicate of #409.

**Closed by bennothommo** 2019-11-15 00:30 UTC
Labels: duplicate

**Comment by Merikamanurung** [comment] 2020-11-27 10:53
need to make confirmation i think
