### ISSUE TITLE
Extending UserModel with repeater field type renders all added fields from whole widget

### ISSUE THREAD

**Issue by snipiba** [rainlab/user-plugin#462] opened 2021-01-01 22:59 UTC
How to reproduce:

On custom plugin try extend user model via 

```
Event::listen('backend.form.extendFields', function($widget) {

$widget->addFields([
                'profile[biography]' => [
                    'label' => 'Biografia',
                    'type' => 'textarea',
                    'size' => 'large',
                    'tab' => 'Social profile',
                    'span' => 'auto'
                ],
                'profile[education]' => [
                    'type' => 'repeater',
                    'label' => 'Vzdelanie',
                    'span' => 'auto',
                    'tab' => 'Extended profile',
                    'form' => [
                        'fields' => [
                            'from_year' => [
                                'type' => 'number',
                                'label' => 'Od roku',
                                'span' => 'auto'
                            ],
                            'to_year' => [
                                'type' => 'number',
                                'label' => 'Do roku',
                                'span' => 'auto'
                            ],
                            'school_name' => [
                                'type' => 'text',
                                'label' => 'Škola',
                                'span' => 'full'
                            ]
                        ]
                    ]
                ],
                'profile[employment]' => [
                    'type' => 'repeater',
                    'label' => 'Zamestnávatelia',
                    'form' => [
                        'fields' => [
                            'company' => [
                                'type' => 'text',
                                'label' => 'Spoločnosť',
                                'span' => 'auto'
                            ],
                            'description' => [
                                'type' => 'textarea',
                                'size' => 'small',
                                'span' => 'auto',
                                'label' => 'Popis práce'
                            ]
                        ]
                    ],
                    'span' => 'auto',
                    'tab' => 'Extended profile',
                ],
....
```

When repeater was rendered in backend, each rendered repeater contains field `profile[biography]` which is false rendered.
Probably it is not issue of rainlab.user plugin, but i will know, how to fix/postpone this issue.

### correct fields
Phone, Website, etc. are correctly showing in main section of Social Profile tab
![Correctly showing fields (phone, website, etc.](https://www.randi.sk/errors/e2.jpg)

### wrong rendering
Same fields as Social Profile showing wrongly in repeater, probably som "check" is needed for generating fields.
![Wrongly showing same fields not only fields in repeater.form.fields](https://www.randi.sk/errors/e1.jpg)

**Comment by LukeTowers** [comment] 2021-01-02 08:25
Duplicate of https://github.com/octobercms/october/issues/5441

**Closed by LukeTowers** 2021-01-02 08:25 UTC
